### ISSUE TITLE
[Bug]: Hydration attribute mismatch errors after upgrading to Nuxt 3.9.0 and Vue 3.4.0

### ISSUE THREAD

**Issue by lotus-x** [radix-vue/radix-vue#577]
### Environment

```bash
Developement/Production OS: Arch Linux
Node version: 20.9.0
Package manager: npm@10.1.0
Radix Vue version: 1.2.5
Vue version: 3.4.0
Nuxt version: 3.9.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.4.0
Client OS: Windows 10 19043.1110
Browser: Chrome 120.0.6099.130
```

### Link to minimal reproduction

https://stackblitz.com/edit/github-shdqqw?file=app.vue

### Steps to reproduce

Encountered when using Collapsible, Tabs, Toggles etc.

Should be reproducible on any radix element which uses Primitive under the hood.

### Describe the bug

This has already reported in few places,

https://github.com/nuxt/nuxt/issues/24994
https://github.com/nuxt/ui/issues/1171

Maybe the current native useId implementation is messed up after the vue update? (https://github.com/nuxt/nuxt/pull/23368)

**Comment by nikuscs** [comment]
Please see : https://github.com/radix-vue/radix-vue/discussions/558

**Comment by lotus-x** [comment]
> Please see : #558

Thanks!

**Comment by adirizky54** [comment]
There is new composable in Nuxt about this issue called `useId` [[SSR-safe accessible unique ID creation](https://nuxt.com/blog/v3-10#ssr-safe-accessible-unique-id-creation)](https://nuxt.com/blog/v3-10#ssr-safe-accessible-unique-id-creation)

**Comment by zernonia** [comment]
Yup @adirizky54 ! Atinux mentioned that to us but we want to have framework agnositc composable. This way anyone using `@vue/server-renderer` also benefit from it.

FYI `useId` composable was planned to release on Vue 3.5 😁

**Comment by BayBreezy** [comment]
I am getting the hydration mismatch warnings in the console for pretty much all the Radix components that use an id internally.
Sadly, I cant pass in my own id.

You are saying we have to just wait until vue releases their useId composable, correct? @zernonia

**Comment by zernonia** [comment]
Hey guys! With [v1.5](https://github.com/radix-vue/radix-vue/pull/718), we've added a workaround for the hydration issue that happened in Nuxt.


```vue
<!-- in Nuxt's app.vue -->
<script setup lang="ts">
import { ConfigProvider } from 'radix-vue'

const useIdFunction = () => useId()
</script>

<template>
  <ConfigProvider :use-id="useIdFunction">
    …
  </ConfigProvider>
</template>
```

**Comment by danielohling** [comment]
> Hey guys! With [v1.5](https://github.com/radix-vue/radix-vue/pull/718), we've added a workaround for the hydration issue that happened in Nuxt.
> 
> ```
> 
> <script setup lang="ts">
> import { ConfigProvider } from 'radix-vue'
> 
> const useIdFunction = () => useId()
> </script>
> 
> <template>
>   <ConfigProvider :use-id="useIdFunction">
>     …
>   </ConfigProvider>
> </template>
> ```

Wonderfull ! 🚀

**Comment by sabiqhasby** [comment]
> Hey guys! With [v1.5](https://github.com/radix-vue/radix-vue/pull/718), we've added a workaround for the hydration issue that happened in Nuxt.
> 
> ```
> 
> <script setup lang="ts">
> import { ConfigProvider } from 'radix-vue'
> 
> const useIdFunction = () => useId()
> </script>
> 
> <template>
>   <ConfigProvider :use-id="useIdFunction">
>     …
>   </ConfigProvider>
> </template>
> ```

Thanks, my problems has been solved.

**Comment by nidhishs** [comment]
> Thanks, my problems has been solved.

@sabiqhasby, by solved, do you mean the warnings no longer show up, or is the UI functional with the warning still visible in the console?

**Comment by Ulrich-Mbouna** [comment]
> Hey guys! With [v1.5](https://github.com/radix-vue/radix-vue/pull/718), we've added a workaround for the hydration issue that happened in Nuxt.
> 
> ```
> 
> <script setup lang="ts">
> import { ConfigProvider } from 'radix-vue'
> 
> const useIdFunction = () => useId()
> </script>
> 
> <template>
>   <ConfigProvider :use-id="useIdFunction">
>     …
>   </ConfigProvider>
> </template>
> ```

And what if  we are using another Css framework like UIkit (getuikit.com) for style and faced hydratation mismatch errors ?

**Comment by insuber** [comment]
@zernonia It seems that the issue still persists in some components, 
 #919 
And I've have the same problem while using **MenubarTrigger**, even after setting up `<ConfigProvider :use-id="useIdFunction">`

**Comment by Ev357** [comment]
> @zernonia It seems that the issue still persists in some components, #919 And I've encountered the same problem while using **MenubarTrigger**, even after setting up `<ConfigProvider :use-id="useIdFunction">`

I also have the same issue with *TabsTrigger*

**Comment by zernonia** [comment]
Thanks @insuber  @Ev357 ! I'll investigate shortly and reopen the ticket if needed ya 😁

**Comment by Ev357** [comment]
Ok, so my dumb mistake, i did not put my `app.vue` into the new `app` folder while i was migrating stuff over to Nuxt 4.

**Comment by michaelsieminski** [comment]
@zernonia this error still happening with Navigation Menu using NuxtLinks the ConfigProvider useId fix doesnt seem to help

**Comment by zernonia** [comment]
@michaelsieminski  can you share a minimal reproduction please? 🙏🏻

**Comment by michaelsieminski** [comment]
> @michaelsieminski can you share a minimal reproduction please? 🙏🏻

I have realized the example in the docs was just wrong as it was using 2 <a> tags, so I made a PR here: https://github.com/radix-vue/shadcn-vue/pull/702
